### ISSUE TITLE
UML STUFF MAKEN. :D

### ISSUE THREAD

**Issue by frankvandennouland** [drakodra/Barricadespel#17]
we moeten al die UML dingen nog afmaken. Ik heb het visio bestand toegevoegd met alles wat ik al had.
de abstracte classen zijn geen abstracte classen dat heeft een andere naam. (aanpassen dus)
[sleutelspel.zip](https://github.com/drakodra/Barricadespel/files/901885/sleutelspel.zip)

**Comment by LucvanderHeiden** [comment]
I did it m8 :)
